### ISSUE TITLE
[Feature Idea] Improve the GitHub Releases creation with auto-publishing `Announcement`s GitHub Discussions

### ISSUE THREAD

**Issue by webknjaz** [jaraco/jaraco.develop#2]
For a while now, when you create a GitHub Release, there's a checkbox `Create a discussion for this release`:
![gh-release-announcement](https://user-images.githubusercontent.com/578543/148294072-c951fa4b-198e-4dc9-a7a3-0457970048ac.png)
When you check it, GitHub automatically creates a discussion that is linked to that release. For example, go to https://github.com/ansible/ansible-language-server/releases/tag/v0.4.0 and you'll see a `Join discussion` button that links https://github.com/ansible/ansible-language-server/discussions/157.

This is very useful to consolidate the feedback post-release, in a dedicated place. I believe the `Announcements` category is auto-created in new repositories with the :mega: icon but for old repos, you'd need to create it once.

Extending https://github.com/jaraco/jaraco.develop/blob/d3e524362ba15f87790f4c6279b1f92c06901387/jaraco/develop/github.py#L71 to pass an extra API arg should be enough, provided that `Discussions` are enabled and the `Announcements` category exists.

**Comment by jaraco** [comment]
jaraco.develop.create-github-release is used in jaraco/skeleton, so applies to hundreds of projects and thus hundreds of repos. I'd be really hesitant to introduce a step that creates a lot of noise and artifacts that's unused, especially if that requires enabling discussions across all of these repos.

In my opinion, if creating a discussion with each release is a good best practice, I'd expect for this change to happen on the Github side automatically.

I'd consider something that allowed a project to opt-in or could adapt based on project settings. With those constraints, would you be willing to draft a proposal?
